// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHfnX3MXFxjTnokuR9d2k0rlQBVACVOfw',
    appId: '1:470859454606:web:61f8c2d031655b00c591df',
    messagingSenderId: '470859454606',
    projectId: 'my-store-8bfbe',
    authDomain: 'my-store-8bfbe.firebaseapp.com',
    storageBucket: 'my-store-8bfbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmu2UKwWJQ19eAe7HjBN_srU-rPk7D2g',
    appId: '1:470859454606:android:a6a075356da6c0b0c591df',
    messagingSenderId: '470859454606',
    projectId: 'my-store-8bfbe',
    storageBucket: 'my-store-8bfbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlHl6u8WSstXp7ExDzjxi2QqmR7QJ6Xlc',
    appId: '1:470859454606:ios:455813c42d02b1c5c591df',
    messagingSenderId: '470859454606',
    projectId: 'my-store-8bfbe',
    storageBucket: 'my-store-8bfbe.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlHl6u8WSstXp7ExDzjxi2QqmR7QJ6Xlc',
    appId: '1:470859454606:ios:455813c42d02b1c5c591df',
    messagingSenderId: '470859454606',
    projectId: 'my-store-8bfbe',
    storageBucket: 'my-store-8bfbe.firebasestorage.app',
    iosBundleId: 'com.example.myStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHfnX3MXFxjTnokuR9d2k0rlQBVACVOfw',
    appId: '1:470859454606:web:728cf392a128dd27c591df',
    messagingSenderId: '470859454606',
    projectId: 'my-store-8bfbe',
    authDomain: 'my-store-8bfbe.firebaseapp.com',
    storageBucket: 'my-store-8bfbe.firebasestorage.app',
  );

}